[80] - Pagina para comentar faculdade
qualfacul/zeus pull request #35
Opened 2016-09-15 21:33 UTC by ericdallo

:warning:  Depende do https://github.com/qualfacul/hades/pull/34 :warning: 

### TO TEST 
ir em posts no perfil da faculdade

2016-09-23 05:00 UTC, andrade-ramon commented on app/views/college_profile.html
> +                                        <input value="" type="submit" class="btn-reply">
remove a borda que fica em volta desse botão
![screen shot 2016-09-23 at 01 59 53](https://cloud.githubusercontent.com/assets/7884943/18774628/7fb7c608-8131-11e6-9b0d-96f4deb132ee.png)

2016-09-23 05:01 UTC, andrade-ramon commented on app/views/college_profile.html
> +                        <label for="comment-switch" class="no-comments-label">Escreva um comentário ou faça uma pergunta</label>
i18n

2016-09-23 05:01 UTC, andrade-ramon commented on app/views/college_profile.html
> +                        <h2>Esta faculdade ainda não tem comentários</h2>
i18n

2016-09-23 05:03 UTC, andrade-ramon commented on app/scripts/controllers/college_profile.js
> +            $route.reload();
cria uma função que carrega todos comentários, e chama ela aqui, dar o reload nessa tela inteira é meio caro.

2016-09-23 05:05 UTC, andrade-ramon commented on app/scripts/controllers/college_profile.js
> +            $route.reload();
cria uma função para carregar os comentários de uma única conversation, e chama ela aqui. Fica caro um reload da página inteira

2016-09-23 05:08 UTC, andrade-ramon commented on app/scripts/controllers/college_profile.js
> +        $http.get(ENV.API.USER.CURRENT).then(function (response) {
não faz mais sentido essa função estar dentro do `user.js`? ai ficaria
```
var user = User.get()
```

2016-09-23 05:12 UTC, andrade-ramon commented on app/scripts/controllers/college_profile.js
> +    $scope.loginThenCommentsUrl =  '/login?redirectAfterLogin=' + encodeURIComponent('/faculdades/' + collegeId);
que tal uma ancora, para já abrir direto na aba de Comentários?

2016-09-23 05:30 UTC, andrade-ramon commented on app/scripts/controllers/college_profile.js
> +    $scope.timeline = {};
separa em uma function especifica de posts

2016-09-23 05:34 UTC, andrade-ramon requested changes

2016-09-23 05:34 UTC, andrade-ramon commented on app/views/college_profile.html
> +                    </article>
Coloca o campo pra fazer uma nova pergunta aqui e remove ele da lateral direita

2016-09-23 05:34 UTC, andrade-ramon commented on app/views/college_profile.html
> +                                        <textarea name="reply" ng-model="reply.text"></textarea>
adiciona um `padding` nessa textarea

2016-09-23 05:34 UTC, andrade-ramon commented on app/views/college_profile.html
> +                                    <h3>{{conversation.messages[0].content}}</h3>
coloca essa primeira mensagem com o mesmo layout de balão das outras mensagens

2016-09-25 04:26 UTC, ericdallo commented on app/scripts/controllers/college_profile.js
> +    $scope.loginThenCommentsUrl =  '/login?redirectAfterLogin=' + encodeURIComponent('/faculdades/' + collegeId);
Não tem como pois a alteração da aba é feita por css e não por html

2016-09-25 04:26 UTC, ericdallo commented on app/scripts/controllers/college_profile.js
> +        $http.get(ENV.API.USER.CURRENT).then(function (response) {
Comecei fazendo isso, ai deu loop infinito de injeção de dependencias... se conseguir descobrir como arrumar podemos trocar.

2016-09-25 04:26 UTC, ericdallo commented on app/scripts/controllers/college_profile.js
> +    $scope.timeline = {};
Nao entendi... esta mockado por enquanto

2016-09-26 18:21 UTC, andrade-ramon approved these changes

2016-09-26 18:21 UTC, merged