[add-student-ratings] - Adiciona avaliacoes de uma faculdade
qualfacul/zeus pull request #84
Opened 2016-10-25 22:20 UTC by ericdallo

### TO TEST
 
clicar no link de avaliações da faculdade na tela de perfil

2016-10-30 17:35 UTC, andrade-ramon requested changes

2016-10-30 17:35 UTC, andrade-ramon commented on app/scripts/controllers/college_conversation.js
> +        if($scope.reply.text === ''){
??

2016-10-30 17:35 UTC, andrade-ramon commented on app/views/college_ratings.html
> +        <h2 class="ratings-title">Avaliações de alunos</h2>
i18n

2016-10-31 23:03 UTC, ericdallo commented on app/scripts/controllers/college_conversation.js
> +        if($scope.reply.text === ''){
por o  angular não atualizar a pagina, isso faz com que ele limpe o campo de texto toda vez que fazer um novo comentario

2016-10-31 23:56 UTC, merged