[I47] - Adiciona busca de cursos
qualfacul/zeus pull request #85
Opened 2016-10-25 22:49 UTC by andrade-ramon

2016-10-30 15:59 UTC, ericdallo requested changes

2016-10-30 15:59 UTC, ericdallo commented on app/scripts/controllers/course_search.js
> +	$scope.search = {};
Thompson

2016-10-30 15:59 UTC, ericdallo commented on app/scripts/controllers/course_search.js
> +                if(course.modality === "PRESENTIAL"){
Da uma olhada [aqui](https://github.com/qualfacul/zeus/pull/84/files#diff-717187983c36bc38f9d9fe97896aa555R1), onde declaro um constante para `ratings`, ve se vc consegue criar uma para os tipos de cursos

2016-10-30 15:59 UTC, ericdallo commented on app/scripts/controllers/course_search.js
> +                switch(course.degree){
Assim voce consegue até criar metodos, e não precisa fazer esse switch... tipo no enum do java

2016-10-30 15:59 UTC, ericdallo commented on app/scripts/directives/header_menu.html
> +					<select id="header-search" class="form-control search-type" ng-model="searchType" ng-options="item as item.label for item in searchItems track by item.id">
:clap:

2016-10-30 17:45 UTC, andrade-ramon commented on app/scripts/controllers/course_search.js
> +	$scope.search = {};
?

2016-11-02 22:22 UTC, ericdallo approved these changes

2016-11-02 22:23 UTC, merged